apiVersion: v1
kind: PersistentVolume
metadata:
    name: mysql-pv
    labels:
        type: local
spec:
    storageClassName: mysql-storage
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: influxdb-pv
    labels:
        type: local
spec:
    storageClassName: influxdb-storage
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/mnt/data"